### ISSUE TITLE
bids convert PRELAPSE

### ISSUE THREAD

**Issue by edickie** [kimjetwav/worganiser#1]

**Comment by edickie** [comment]
remember that all subject ID's that start with an "R" are actually at "repeat" scan of the same person and timepoint 
In general - we might just ignore the "PRE**" prefix entirely.
In general - we want a 5 digit subject id for everyone..

**Comment by kimjetwav** [comment]
Hey Erin, what the heck are EH, LH, and S scans?

I found this list of scans with the subject ID prefixed by these letters:

> data/RESOURCES/PRE01_PCE_S2025_01_01
> data/mnc/PRE01_SFD_32013_02
> data/mnc/PRE01_SFD_32013_03
> data/mnc/PRE01_PCE_S2025_03
> data/mnc/PRE01_PCE_S2015_02
> data/mnc/PRE01_SFD_32002_01
> data/mnc/PRE01_SFD_32002_03
> data/mnc/PRE01_SFD_32016_01
> data/mnc/PRE01_PCE_S02014_02
> data/mnc/PRE01_CTN_LH14016_03
> data/mnc/PRE01_PCE_S2016_01
> data/mnc/PRE01_PCE_S2013_03
> data/mnc/PRE01_CTN_EH14014_01
> data/mnc/PRE01_SFD_32013_01
> data/mnc/PRE01_PCE_S2026_03
> data/mnc/PRE01_PCE_S2013_02
> data/mnc/PRE01_SFD_32014_02
> data/mnc/PRE01_PCE_S2021_01
> data/mnc/PRE01_SFD_32002_02
> data/mnc/PRE01_SFD_32016_03
> data/mnc/PRE01_PCE_S2014_02
> data/mnc/PRE01_PCE_S2025_01
> data/mnc/PRE01_SFD_32011_01
> data/mnc/PRE01_PCE_S2021_02
> data/mnc/PRE01_SFD_32014_03
> data/mnc/PRE01_CTN_LH14016_02
> data/mnc/PRE01_PCE_S2026_02
> data/mnc/PRE01_PCE_S02016_01
> data/mnc/PRE01_SFD_32014_01
> data/mnc/PRE01_CTN_LH14016_01
> data/mnc/PRE01_PCE_S2014_03
> data/mnc/PRE01_PCE_S2015_03
> data/mnc/PRE01_PCE_S02014_01
> data/mnc/PRE01_PCE_S2022_02
> data/mnc/PRE01_CTN_EH14014_02
> data/mnc/PRE01_SFD_32016_02
> data/mnc/PRE01_PCE_S2022_01
> data/mnc/PRE01_PCE_S2014_01
> data/mnc/PRE01_PCE_S2020_01
> data/mnc/PRE01_CTN_EH14014_03
> data/nrrd/PRE01_SFD_32013_02
> data/nrrd/PRE01_SFD_32013_03
> data/nrrd/PRE01_PCE_S2025_03
> data/nrrd/PRE01_PCE_S2015_02
> data/nrrd/PRE01_SFD_32002_01
> data/nrrd/PRE01_SFD_32002_03
> data/nrrd/PRE01_SFD_32016_01
> data/nrrd/PRE01_PCE_S02014_02
> data/nrrd/PRE01_CTN_LH14016_03
> data/nrrd/PRE01_PCE_S2016_01
> data/nrrd/PRE01_PCE_S2013_03
> data/nrrd/PRE01_CTN_EH14014_01
> data/nrrd/PRE01_SFD_32013_01
> data/nrrd/PRE01_PCE_S2026_03
> data/nrrd/PRE01_PCE_S2013_02
> data/nrrd/PRE01_SFD_32014_02
> data/nrrd/PRE01_PCE_S2021_01
> data/nrrd/PRE01_SFD_32002_02
> data/nrrd/PRE01_SFD_32016_03
> data/nrrd/PRE01_PCE_S2014_02
> data/nrrd/PRE01_SFD_32011_01
> data/nrrd/PRE01_PCE_S2021_02
> data/nrrd/PRE01_SFD_32014_03
> data/nrrd/PRE01_CTN_LH14016_02
> data/nrrd/PRE01_PCE_S02016_01
> data/nrrd/PRE01_SFD_32014_01
> data/nrrd/PRE01_CTN_LH14016_01
> data/nrrd/PRE01_PCE_S2014_03
> data/nrrd/PRE01_PCE_S2015_03
> data/nrrd/PRE01_PCE_S02014_01
> data/nrrd/PRE01_PCE_S2022_02
> data/nrrd/PRE01_CTN_EH14014_02
> data/nrrd/PRE01_SFD_32016_02
> data/nrrd/PRE01_PCE_S2022_01
> data/nrrd/PRE01_PCE_S2014_01
> data/nrrd/PRE01_CTN_EH14014_03
> data/nii/PRE01_SFD_32013_02
> data/nii/PRE01_SFD_32013_03
> data/nii/PRE01_PCE_S2025_03
> data/nii/PRE01_PCE_S2015_02
> data/nii/PRE01_SFD_32002_01
> data/nii/PRE01_SFD_32002_03
> data/nii/PRE01_SFD_32016_01
> data/nii/PRE01_PCE_S02014_02
> data/nii/PRE01_CTN_LH14016_03
> data/nii/PRE01_PCE_S2016_01
> data/nii/PRE01_PCE_S2013_03
> data/nii/PRE01_CTN_EH14014_01
> data/nii/PRE01_SFD_32013_01
> data/nii/PRE01_PCE_S2026_03
> data/nii/PRE01_PCE_S2013_02
> data/nii/PRE01_SFD_32014_02
> data/nii/PRE01_PCE_S2021_01
> data/nii/PRE01_SFD_32002_02
> data/nii/PRE01_SFD_32016_03
> data/nii/PRE01_PCE_S2014_02
> data/nii/PRE01_PCE_S2025_01
> data/nii/PRE01_SFD_32011_01
> data/nii/PRE01_PCE_S2021_02
> data/nii/PRE01_SFD_32014_03
> data/nii/PRE01_CTN_LH14016_02
> data/nii/PRE01_PCE_S2026_02
> data/nii/PRE01_PCE_S02016_01
> data/nii/PRE01_SFD_32014_01
> data/nii/PRE01_CTN_LH14016_01
> data/nii/PRE01_PCE_S2014_03
> data/nii/PRE01_PCE_S2015_03
> data/nii/PRE01_PCE_S02014_01
> data/nii/PRE01_PCE_S2022_02
> data/nii/PRE01_CTN_EH14014_02
> data/nii/PRE01_SFD_32016_02
> data/nii/PRE01_PCE_S2022_01
> data/nii/PRE01_PCE_S2014_01
> data/nii/PRE01_PCE_S2020_01
> data/nii/PRE01_CTN_EH14014_03
> data/bkup/PRE01_SFD_32014_01_01.zip
> data/dcm/PRE01_SFD_32013_02
> data/dcm/PRE01_SFD_32013_03
> data/dcm/PRE01_PCE_S2025_03
> data/dcm/PRE01_PCE_S2015_02
> data/dcm/PRE01_SFD_32002_01
> data/dcm/PRE01_SFD_32002_03
> data/dcm/PRE01_SFD_32016_01
> data/dcm/PRE01_PCE_S02014_02
> data/dcm/PRE01_CTN_LH14016_03
> data/dcm/PRE01_PCE_S2016_01
> data/dcm/PRE01_PCE_S2013_03
> data/dcm/PRE01_CTN_EH14014_01
> data/dcm/PRE01_SFD_32013_01
> data/dcm/PRE01_PCE_S2026_03
> data/dcm/PRE01_PCE_S2013_02
> data/dcm/PRE01_SFD_32014_02
> data/dcm/PRE01_PCE_S2021_01
> data/dcm/PRE01_SFD_32002_02
> data/dcm/PRE01_SFD_32016_03
> data/dcm/PRE01_PCE_S2014_02
> data/dcm/PRE01_PCE_S2025_01
> data/dcm/PRE01_SFD_32011_01
> data/dcm/PRE01_PCE_S2021_02
> data/dcm/PRE01_SFD_32014_03
> data/dcm/PRE01_CTN_LH14016_02
> data/dcm/PRE01_PCE_S2026_02
> data/dcm/PRE01_PCE_S02016_01
> data/dcm/PRE01_SFD_32014_01
> data/dcm/PRE01_CTN_LH14016_01
> data/dcm/PRE01_PCE_S2014_03
> data/dcm/PRE01_PCE_S2015_03
> data/dcm/PRE01_PCE_S02014_01
> data/dcm/PRE01_PCE_S2022_02
> data/dcm/PRE01_CTN_EH14014_02
> data/dcm/PRE01_SFD_32016_02
> data/dcm/PRE01_PCE_S2022_01
> data/dcm/PRE01_PCE_S2014_01
> data/dcm/PRE01_PCE_S2020_01
> data/dcm/PRE01_CTN_EH14014_03

**Comment by kimjetwav** [comment]
`PRELAPSE` has been mostly BIDS-converted, and we can not begin to run fmriprep and ciftify on it.

**Comment by edickie** [comment]
wait can or can not?

**Comment by kimjetwav** [comment]
We can NOW***
The extra B is for BYOBB.
That extra B was a typo.

**Comment by kimjetwav** [comment]
Running fmriprep into my scratch for now using Jerry's nextflow invocation. Doot.

**Comment by kimjetwav** [comment]
This is bids converted and done we’re generating outputs on it. We can re-open if there’s a bigger problem with the naming or something.
